From tmatsuo/centos:7

RUN yum install -y python2-pip.noarch python-tornado.x86_64 supervisor && \
    pip install butterfly
RUN echo -e "## CentOS 7 Web Console ##\n\n" > /etc/motd && \
    sed -i "s/nodaemon=false/nodaemon=true/g" /etc/supervisord.conf

RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG='ja_JP.utf8' LANGUAGE='ja_JP:ja' LC_ALL='ja_JP.UTF-8'

COPY ./docker-entrypoint.sh /
COPY ./butterfly.ini /etc/supervisord.d/

ENTRYPOINT ["/docker-entrypoint.sh"]
